# Generated by Django 4.1.7 on 2023-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_date_onf_birth_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
