# Generated by Django 4.1.7 on 2023-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_measurements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
